[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-storage-blob>=12.29.0",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "joblib>=1.5.3",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.47.0",
    "xgboost>=3.2.0",
]
